# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='clothing',
            options={'verbose_name_plural': 'Clothing'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
