# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20151226_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='clothingType',
            new_name='name',
        ),
    ]
